### PR TITLE
Fixes phylogeny's sequential-njoining algorithm crashes

### LINKED ISSUE #20: Sequential neighbor-joining algorithm crashes when running in parallel
When running the phylogeny module with a distributed sequential version of the neighbor-joining algorithm, a crash happens when the number of sequences to align is too low.

The thrown exception's message is related to a buffer offset out of range, which is a clue that a slave node is trying to do work when there's none assigned to it.

A possible fix is to limit the number of workers depending on the amount of nodes on the algorithm's star-tree.

### PR DESCRIPTION
**Pull request by rodriados**
Fixes #20 a bug found on the phylogeny's module sequential-njoining algorithm, where it would crash when the number of cluster worker-nodes was smaller than the total number of OTUs on the star-tree.

The fix was done simply implementing the verification previously present on the hybrid version of the same algorithm.

### CODE REVIEW

File: src/phylogeny/njoining/sequential.cpp [hunk 1]
```diff
@@ -273,19 +273,23 @@ namespace
...
+                    #if !defined(__museqa_runtime_cython)
+                        const auto workers = utils::min<size_t>(node::count - 1, star.count - 1);
+                        onlyslaves partition = utils::partition(total, workers, node::rank - 1);
+                    #else
+                        partition = range<size_t> {0, total};
+                    #endif
+
+                    // After finding each compute node's local best joinable candidate,
+                    // we must gather the votes and find the best one globally.
+                    onlyslaves vote = pick_joinable(star, partition);
```
Comment (rodriados) [inline src/phylogeny/njoining/sequential.cpp:290]: The keyword `onlyslaves` may not be necessary here, as it's already in this context.
